### ISSUE TITLE
Supported standard version needed in documentation

### ISSUE THREAD

**Issue by SmaugPool** [tasuki/elm-punycode#1]
Hi and thank you very much for this punycode decoder!

It would be really useful to precisely indicate which standard and features are supported in the documentation (IDNA 2008, 2003, transitional features, UTS 46. etc.).

Thank you

**Comment by tasuki** [comment]
I have the first user hooray! Unfortunately I must disappoint you, I know nothing about these things you mention and I'm pretty sure I wasn't following any standard.

For the Punycode part, I just took the examples from Wikipedia, turned them into test cases, and hammered at it until the tests started passing. The IDNA, I strip the `xn--` part if present and pass it to the Punycode decoder. No lowercasing or anything :shrug:

**Comment by SmaugPool** [comment]
That's fine and exactly what I needed anyway ;)

I guess we could say it follows [RFC 3492](https://www.rfc-editor.org/rfc/rfc3492) with additional [ACE prefix support](https://en.wikipedia.org/wiki/Punycode#ACE_prefix_for_internationalized_domain_names).

**Comment by tasuki** [comment]
Cheers, added a mention to the [module documentation](https://package.elm-lang.org/packages/tasuki/elm-punycode/latest/Punycode)!
